# Generated by Django 4.2.6 on 2023-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.RemoveField(
            model_name='react',
            name='employee',
        ),
        migrations.AddField(
            model_name='react',
            name='name',
            field=models.CharField(default='default_tables_value', max_length=100),
        ),
        migrations.AddField(
            model_name='react',
            name='narrator',
            field=models.CharField(default='default_narrator_value', max_length=100),
        ),
        migrations.AddField(
            model_name='react',
            name='theme',
            field=models.CharField(default='default_theme_value', max_length=100),
        ),
    ]
