# Generated by Django 4.2.6 on 2023-10-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_react_department_remove_react_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='narrator',
            new_name='narratortitle',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='narratorname',
            field=models.CharField(default='default_theme_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='react',
            name='theme',
            field=models.CharField(default='default_tables_value', max_length=100),
        ),
    ]
